import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft,faArrowRight,faArrowUpRightFromSquare,faCheck } from "@fortawesome/free-solid-svg-icons";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ProjectImagePlaceholder } from "@/components/ProjectImagePlaceholder";
import { getProject,projects } from "@/data/projects";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return projects.map(({slug})=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const project=getProject((await params).slug);return project?{title:project.name,description:project.summary}:{} }

export default async function ProjectPage({params}:Props){const project=getProject((await params).slug);if(!project)notFound();const index=projects.findIndex(item=>item.slug===project.slug);const next=projects[(index+1)%projects.length];return <><Header/><main id="top" className="pt-[76px]"><article><header className="border-b border-[var(--line)] bg-white py-16 sm:py-20"><div className="project-detail-container"><Link href="/#projects" className="focus-ring inline-flex min-h-11 items-center gap-2 font-extrabold"><FontAwesomeIcon icon={faArrowLeft} className="h-3"/>All projects</Link><div className="mt-9 grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="eyebrow text-[var(--orange)]">Personal Project · {project.status}</p><h1 className="display mt-5 text-5xl font-extrabold leading-[.98] sm:text-7xl">{project.name}</h1><p className="mt-4 text-sm font-extrabold uppercase tracking-wider text-[var(--muted)]">{project.category}</p><p className="mt-6 text-xl leading-8 text-[var(--muted)]">{project.summary}</p>{project.liveUrl&&<a href={project.liveUrl} target="_blank" rel="noreferrer" className="button button-primary mt-7">Open live demo <FontAwesomeIcon icon={faArrowUpRightFromSquare} className="h-3"/></a>}</div><div className="overflow-hidden rounded-2xl"><ProjectMedia project={project}/></div></div></div></header>
  <div className="case-detail-container py-16 sm:py-24"><ProjectSection number="01" title="Overview"><p>{project.overview}</p>{project.disclaimer&&<p className="mt-5 rounded-xl border border-[var(--line)] bg-white p-4 text-sm font-bold">{project.disclaimer}</p>}</ProjectSection><ProjectSection number="02" title="Problem / Motivation"><p>{project.motivation}</p></ProjectSection><ProjectSection number="03" title="What I Built"><CheckList items={project.contributions}/></ProjectSection><ProjectSection number="04" title="Key Features"><CheckList items={project.features}/></ProjectSection><ProjectSection number="05" title="Technical Architecture"><Architecture project={project}/></ProjectSection><ProjectSection number="06" title="Engineering Challenges"><div className="grid gap-4">{project.challenges.map(challenge=><article key={challenge.title} className="rounded-xl border border-[var(--line)] bg-white p-5"><h3 className="display text-xl font-extrabold">{challenge.title}</h3><p className="mt-4"><strong className="text-[var(--ink)]">Approach:</strong> {challenge.approach}</p><p className="mt-2"><strong className="text-[var(--ink)]">Result:</strong> {challenge.result}</p></article>)}</div></ProjectSection><ProjectSection number="07" title="QA & Testing"><p className="mb-5">Building the product also meant testing it from a user, integration, and failure-boundary perspective.</p><CheckList items={project.testing}/></ProjectSection>{project.security&&<ProjectSection number="08" title="Security / Reliability"><CheckList items={project.security}/></ProjectSection>}<ProjectSection number="09" title="Tech Stack"><div className="flex flex-wrap gap-2">{project.stack.map(tech=><span className="pill bg-white" key={tech}>{tech}</span>)}</div></ProjectSection><ProjectSection number="10" title="Current Status"><span className="pill border-[var(--ink)] bg-[var(--mint)]">{project.status}</span></ProjectSection><ProjectSection number="11" title="Links"><div className="flex flex-wrap gap-3">{project.liveUrl?<a href={project.liveUrl} target="_blank" rel="noreferrer" className="button button-primary">Live demo <FontAwesomeIcon icon={faArrowUpRightFromSquare} className="h-3"/></a>:<p>No public project link is currently available.</p>}{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noreferrer" className="button">GitHub</a>}</div></ProjectSection>
  <nav className="mt-12 flex justify-end border-t border-[var(--line)] pt-8" aria-label="Project pagination"><Link href={`/projects/${next.slug}`} className="group flex w-full max-w-sm items-center justify-between gap-4 rounded-2xl border border-[var(--ink)] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_7px_0_var(--ink)]"><div><span className="text-xs font-extrabold uppercase tracking-wider text-[var(--orange)]">Next project</span><p className="display mt-1 text-xl font-extrabold">{next.name}</p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-[var(--ink)] text-white"><FontAwesomeIcon icon={faArrowRight} className="h-4"/></span></Link></nav></div></article></main><Footer/></>}

function ProjectMedia({project}:{project:(typeof projects)[number]}){const screenshot=project.screenshots?.[0];return screenshot?<div className="relative aspect-[16/10]"><Image src={screenshot.src} alt={screenshot.alt} fill sizes="(max-width:1024px) 100vw,45vw" className="object-contain"/></div>:<ProjectImagePlaceholder projectName={project.name} projectType={project.type}/>}
function ProjectSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="case-detail-section"><div className="flex items-baseline gap-4"><span className="text-xs font-extrabold text-[var(--orange)]">{number}</span><h2 className="display text-3xl font-extrabold sm:text-4xl">{title}</h2></div><div className="case-detail-copy mt-6 leading-8 text-[var(--muted)]">{children}</div></section>}
function CheckList({items}:{items:string[]}){return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className="flex gap-3 leading-7"><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[var(--mint)] text-[.62rem] text-[var(--ink)]"><FontAwesomeIcon icon={faCheck}/></span>{item}</li>)}</ul>}
function Architecture({project}:{project:(typeof projects)[number]}){return <div className="architecture-flow"><div className="architecture-node"><span>Experience</span><strong>{project.architecture.client}</strong></div><span aria-hidden="true">↓</span><div className="architecture-node"><span>Application</span><strong>{project.architecture.application}</strong></div><span aria-hidden="true">↓</span><div className="grid w-full gap-2 sm:grid-cols-2">{project.architecture.services.map(service=><div className="architecture-node" key={service}><span>Service</span><strong>{service}</strong></div>)}</div>{project.architecture.delivery&&<><span aria-hidden="true">↓</span><div className="architecture-node"><span>Delivery</span><strong>{project.architecture.delivery}</strong></div></>}</div>}
