import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight,faCheck,faCodeBranch,faBug,faFlask,faMagnifyingGlass,faPenToSquare,faRotate,faRocket } from "@fortawesome/free-solid-svg-icons";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { CaseStudies } from "@/components/CaseStudies";
import { missingReceiptBug } from "@/data/qaArtifacts";

const skillGroups=[
  ["Core testing",["Manual Testing","Exploratory Testing","Functional Testing","Regression Testing","Smoke Testing","End-to-End Testing","Integration Testing"]],
  ["Product experience",["UI/UX Testing","Cross-Browser Testing","Responsive Testing","Mobile Testing","Localization Testing","Export Validation"]],
  ["Technical QA",["API Testing","Database Validation","Bug Reporting","Test Case Design","Test Planning","Release Verification"]],
];
const tools=[
  ["Daily QA",["Jira","Postman","Chrome DevTools","GitHub","Azure DevOps"]],
  ["Cross-platform",["BrowserStack","Sauce Labs"]],
  ["Technical background",["SQL","MySQL","PHP","JavaScript","Git"]],
  ["Automation familiarity",["Cypress","Selenium"]],
];
const process=[
  [faMagnifyingGlass,"Understand","Clarify the user, change, and intended behavior."],
  [faFlask,"Identify risk","Prioritize impact, likelihood, and fragile boundaries."],
  [faCodeBranch,"Design coverage","Map workflows, data, configurations, and platforms."],
  [faCheck,"Test & explore","Verify expectations, then investigate beyond the script."],
  [faPenToSquare,"Document","Share concise evidence and reproducible findings."],
  [faRotate,"Re-test","Confirm the fix and check adjacent behavior for regressions."],
  [faRocket,"Release confidence","Communicate what was tested, what passed, and residual risk."],
];

export default function Home(){return <><Header/><main id="top">
  <section className="relative min-h-[720px] overflow-hidden pt-[76px] grid-lines"><div className="hero-orb absolute -right-32 top-16 h-[520px] w-[520px] rounded-full bg-[var(--mint)]/45 blur-3xl"/><div className="container relative grid min-h-[644px] items-center gap-12 py-16 lg:grid-cols-[1.3fr_.7fr]">
    <div><span className="pill bg-white/70"><span className="h-2 w-2 rounded-full bg-green-600"/>Available for Remote QA Opportunities</span><h1 className="display mt-7 max-w-4xl text-[clamp(3.25rem,7.8vw,7rem)] font-extrabold leading-[.92]">I find what<br/>others <span className="relative inline-block text-[var(--orange)]">miss.<svg className="absolute -bottom-3 left-0 w-full" viewBox="0 0 350 18" aria-hidden="true"><path d="M3 12C94 3 239 5 347 9" fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg></span></h1><p className="mt-9 max-w-3xl text-lg leading-8 text-[var(--muted)] sm:text-xl">QA Engineer with 3+ years of dedicated software testing experience, backed by 8+ years in software development. I test web and mobile products through exploratory, regression, API, cross-browser, responsive, and end-to-end testing.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#case-studies" className="button button-primary">View my work <FontAwesomeIcon icon={faArrowRight} className="h-4"/></a><a href="#contact" className="button bg-white/70">Contact me</a></div></div>
    <aside className="relative hidden lg:block" aria-label="Professional highlights"><div className="rotate-2 rounded-[2rem] border border-[var(--ink)] bg-white p-6 shadow-[16px_16px_0_var(--ink)]"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[var(--orange)]">QA at a glance</p><h2 className="display mt-3 text-2xl font-extrabold">Breadth built on technical depth.</h2><div className="mt-6">{["Web, iOS & Android Testing","Manual & Exploratory QA","API & Regression Testing","Cross-Browser Testing","8+ Years Development Background"].map(item=><div key={item} className="flex items-center gap-3 border-t border-[var(--line)] py-4 text-sm font-bold"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[var(--mint)]"><FontAwesomeIcon icon={faCheck} className="h-3"/></span>{item}</div>)}</div></div></aside>
  </div></section>

  <section id="about" className="section scroll-mt-16 bg-white"><div className="container grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-[var(--orange)]">About</p><div className="mt-9 grid h-28 w-28 place-items-center rounded-full border-2 border-[var(--ink)] bg-[var(--mint)] text-4xl" aria-hidden="true">✦</div></div><div><h2 className="display text-4xl font-extrabold leading-tight sm:text-6xl">A tester who understands how software gets built.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">I spent years building and maintaining web applications before focusing professionally on software quality. That background helps me investigate beyond the surface, understand how frontend, backend, databases, and APIs interact, and communicate findings clearly with developers and product stakeholders.</p><p className="mt-4 max-w-3xl text-lg leading-8 text-[var(--muted)]">I combine structured coverage with curiosity, looking closely at configuration boundaries, real user workflows, and the risks around each change.</p></div></div></section>

  <section id="experience" className="section scroll-mt-16"><div className="container"><p className="eyebrow text-[var(--orange)]">Professional experience</p><h2 className="display mt-6 text-5xl font-extrabold sm:text-7xl">Built to test. Trained to build.</h2><div className="mt-14 grid gap-5 lg:grid-cols-2">
    <article className="experience-card border-t-[6px] border-t-[var(--orange)]"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-extrabold uppercase tracking-wider text-[var(--orange)]">2023 - Present</p><h3 className="display mt-3 text-3xl font-extrabold">Test Engineer</h3><p className="mt-1 font-bold">Abukai Incorporated</p></div><span className="pill self-start">Current role</span></div><p className="mt-7 leading-7 text-[var(--muted)]">Manual QA for web, iOS, and Android products across feature, release, and configuration-driven workflows.</p><ul className="check-list mt-6">{["Functional, exploratory, regression, smoke, and end-to-end testing","Cross-browser, responsive, real-device, and localization testing","API validation with Postman and export validation for PDF, CSV, and XLSX","Approval workflow testing, detailed bug reporting, and fix verification","Test plans, test cases, matrices, QA timeboxes, and release validation"].map(item=><li key={item}>{item}</li>)}</ul></article>
    <article className="experience-card border-t-[6px] border-t-[var(--mint)]"><p className="text-sm font-extrabold uppercase tracking-wider text-[var(--muted)]">Approximately 8 years</p><h3 className="display mt-3 text-3xl font-extrabold">Software Engineer / Web Developer</h3><p className="mt-7 leading-7 text-[var(--muted)]">Developed and maintained web applications using PHP, CodeIgniter, Laravel, AngularJS, JavaScript, jQuery, HTML/CSS, MySQL, MSSQL, and Git.</p><div className="mt-8 rounded-2xl bg-[var(--ink)] p-6 text-white"><h4 className="font-extrabold text-[var(--mint)]">The QA advantage</h4><p className="mt-3 leading-7 text-white/75">Development experience gives me context for application architecture, debugging, API behavior, database state, frontend interactions, and the workflows developers use to deliver fixes.</p></div></article>
  </div></div></section>

  <section id="case-studies" className="section scroll-mt-16 bg-white"><div className="container"><div className="grid gap-6 lg:grid-cols-[1fr_.55fr] lg:items-end"><div><p className="eyebrow text-[var(--orange)]">Selected case studies</p><h2 className="display mt-6 text-5xl font-extrabold sm:text-7xl">QA thinking in practice.</h2></div><p className="leading-7 text-[var(--muted)]">Sanitized examples based on real types of work. Select a case study to see the problem, coverage, approach, risks, and outcome.</p></div><CaseStudies/></div></section>

  <section id="skills" className="section scroll-mt-16"><div className="container"><p className="eyebrow text-[var(--orange)]">Skills & tools</p><div className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><h2 className="display text-5xl font-extrabold sm:text-6xl">Coverage with structure.</h2><p className="max-w-2xl text-lg leading-8 text-[var(--muted)]">A practical toolkit for understanding changes, testing the right risks, and communicating results teams can act on.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{skillGroups.map(([title,items])=><article key={title as string} className="skill-card"><h3 className="display text-xl font-extrabold">{title}</h3><ul className="mt-5 space-y-3">{(items as string[]).map(item=><li key={item} className="flex gap-3 text-sm"><span className="text-[var(--orange)]">●</span>{item}</li>)}</ul></article>)}</div><h3 className="display mt-16 text-3xl font-extrabold">Tools & technologies</h3><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tools.map(([title,items])=><article key={title as string} className="rounded-2xl border border-[var(--line)] bg-white p-5"><h4 className="text-xs font-extrabold uppercase tracking-[.14em] text-[var(--orange)]">{title}</h4><p className="mt-4 leading-7 text-[var(--muted)]">{(items as string[]).join(" / ")}</p></article>)}</div></div></section>

  <section id="qa-artifact" className="section scroll-mt-16 bg-[var(--ink)] text-white"><div className="container"><div className="grid gap-6 lg:grid-cols-[1fr_.55fr] lg:items-end"><div><p className="eyebrow text-[var(--mint)]">QA in practice</p><h2 className="display mt-6 text-5xl font-extrabold sm:text-7xl">A useful bug report removes guesswork.</h2></div><p className="leading-7 text-white/65">This sanitized sample demonstrates documentation style only. It contains no private account data or confidential implementation detail.</p></div><article className="mt-12 overflow-hidden rounded-[1.75rem] border border-white/15 bg-white text-[var(--ink)]"><header className="flex flex-col gap-4 border-b border-[var(--line)] bg-[var(--cream)] p-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-[var(--orange)]">Sanitized bug report</p><h3 className="display mt-2 max-w-3xl text-2xl font-extrabold">{missingReceiptBug.title}</h3></div><span className="pill self-start !border-amber-300 !bg-amber-50 text-amber-800">{missingReceiptBug.severity}</span></header><div className="grid gap-px bg-[var(--line)] md:grid-cols-2"><Artifact label="Environment" text={missingReceiptBug.environment}/><Artifact label="Preconditions" text={missingReceiptBug.preconditions}/><div className="bg-white p-6 md:col-span-2"><h4 className="detail-title">Steps to reproduce</h4><ol className="mt-4 list-decimal space-y-2 pl-5 leading-7 text-[var(--muted)]">{missingReceiptBug.steps.map(step=><li key={step}>{step}</li>)}</ol></div><Artifact label="Expected" text={missingReceiptBug.expected}/><Artifact label="Actual" text={missingReceiptBug.actual}/><Artifact label="Impact" text={missingReceiptBug.impact}/><Artifact label="Evidence" text={missingReceiptBug.evidence}/></div></article></div></section>

  <section className="section bg-[var(--mint)]"><div className="container"><p className="eyebrow">Risk-based QA process</p><h2 className="display mt-6 max-w-4xl text-5xl font-extrabold sm:text-7xl">More than running test cases.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{process.map(([icon,title,copy],index)=><article key={String(title)} className="relative rounded-2xl border border-[var(--ink)] bg-[var(--cream)] p-6"><span className="absolute right-4 top-4 text-xs font-extrabold opacity-40">0{index+1}</span><FontAwesomeIcon icon={icon as typeof faBug} className="h-5 text-[var(--orange)]"/><h3 className="display mt-8 text-xl font-extrabold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{String(copy)}</p></article>)}</div></div></section>
</main><Footer/></>}

function Artifact({label,text,wide=false}:{label:string;text:string;wide?:boolean}){return <div className={`bg-white p-6 ${wide?"md:col-span-2":""}`}><h4 className="detail-title">{label}</h4><p className="mt-3 leading-7 text-[var(--muted)]">{text}</p></div>}
