"use client";
import { useEffect, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight, faXmark } from "@fortawesome/free-solid-svg-icons";

type Study={number:string;title:string;problem:string;scope:string;tested:string[];approach:string;tools:string[];risks:string;outcome:string};
const studies:Study[]=[
  {number:"01",title:"Missing Receipt Warning Validation",problem:"Users need a clear warning when submitting or exporting expenses without receipts.",scope:"Warning behavior across account types, policy values, user preferences, and submit/export workflows.",tested:["Free, individual, and corporate accounts","Policy values: No, Yes, and User","Preference persistence and standard/custom fields","One, multiple, and no missing receipts","Submit for Approval, Export, and Merge","Cancel/No behavior and continuation after Yes"],approach:"Built a configuration matrix first, then exercised each state through the full workflow and re-tested persistence after refresh and sign-in.",tools:["Jira","Chrome DevTools","BrowserStack"],risks:"Account-level configuration overriding user intent, inconsistent warning triggers, and destructive actions continuing after cancel.",outcome:"Established traceable coverage for a configuration-heavy safeguard without exposing production account details."},
  {number:"02",title:"Statistics & Report Archive",problem:"Users need reliable statistics, filters, exports, and access to archived reports across large result sets.",scope:"Graphs, filter combinations, report archives, document exports, and infinite scrolling.",tested:["Year, month, week, and day graph views","Employee, location, units, category, and project filters","Department, payment type, and tag filters","XLSX, PDF, CSV, receipt image, and document exports","Archived records and infinite scrolling","More than 100 scenarios considered for the statistics area"],approach:"Partitioned coverage by data dimension and output type, then combined high-risk filters to verify counts, graphs, files, and archived data stayed consistent.",tools:["Postman","Chrome DevTools","SQL","Jira"],risks:"Mismatched totals, stale filters, truncated exports, duplicate paginated records, and archive visibility errors.",outcome:"Created a repeatable regression model spanning UI presentation, underlying data, and downloaded output."},
  {number:"03",title:"Localization & Browser Locale Testing",problem:"Descriptions and interface content must use the correct locale with a reliable fallback language.",scope:"Profile language, browser locale, translation availability, fallback behavior, and browser differences.",tested:["English / en-US, German / de-DE, French / fr-FR","Croatian and Japanese locales","Unsupported browser locales","Missing and partial translations","English fallback behavior","Cross-browser locale configuration"],approach:"Used a locale matrix to separate application preference from browser behavior and verified both translated content and fallback paths.",tools:["BrowserStack","Sauce Labs","Chrome DevTools"],risks:"Mixed-language screens, silent missing keys, incorrect regional formatting, and browser-specific locale selection.",outcome:"Documented predictable fallback behavior and surfaced combinations that would otherwise be easy to miss."},
  {number:"04",title:"Edit Expenses Regression Testing",problem:"A complex, configuration-driven expenses interface must remain stable across releases.",scope:"Regression and exploratory coverage across controls, report states, account settings, and responsive layouts.",tested:["Sorting, standard fields, and custom fields","Floating actions, tooltips, and support dialog","Locked reports and receipt review","Corporate user and collapsible settings","Report totals and expense selection","Indicators, loading states, and responsive layouts"],approach:"Combined a stable regression checklist with exploratory charters around changed areas, adjacent workflows, and configuration boundaries.",tools:["Jira","BrowserStack","Postman","Chrome DevTools"],risks:"State loss, incorrect totals, unavailable actions, misleading loading behavior, and controls breaking at smaller widths.",outcome:"Balanced broad release coverage with targeted investigation of the areas most likely to regress."},
];

export function CaseStudies(){const [selected,setSelected]=useState<Study|null>(null);useEffect(()=>{if(!selected)return;const close=(event:KeyboardEvent)=>event.key==="Escape"&&setSelected(null);document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[selected]);return <>
  <div className="mt-12 grid gap-5 md:grid-cols-2">{studies.map(study=><article key={study.number} className="case-card"><div className="flex items-start justify-between gap-4"><span className="display text-3xl font-extrabold text-[var(--orange)]">{study.number}</span><span className="pill !py-1.5">Sanitized</span></div><h3 className="display mt-8 text-2xl font-extrabold sm:text-3xl">{study.title}</h3><p className="mt-4 leading-7 text-[var(--muted)]">{study.problem}</p><button onClick={()=>setSelected(study)} className="focus-ring mt-8 inline-flex min-h-11 items-center gap-2 self-start font-extrabold">View QA approach <FontAwesomeIcon icon={faArrowRight} className="h-3"/></button></article>)}</div>
  {selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-[var(--ink)]/70 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-labelledby="case-title" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><article className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-[1.75rem] bg-[var(--cream)] p-6 shadow-2xl sm:p-10"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow text-[var(--orange)]">Case study {selected.number}</p><h3 id="case-title" className="display mt-4 text-3xl font-extrabold sm:text-5xl">{selected.title}</h3></div><button autoFocus onClick={()=>setSelected(null)} className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[var(--line)]" aria-label="Close case study"><FontAwesomeIcon icon={faXmark}/></button></div><div className="mt-9 grid gap-7 md:grid-cols-2"><Detail title="Problem" text={selected.problem}/><Detail title="QA Scope" text={selected.scope}/><div className="md:col-span-2"><h4 className="detail-title">What I Tested</h4><ul className="mt-3 grid gap-2 sm:grid-cols-2">{selected.tested.map(item=><li key={item} className="flex gap-3 leading-6"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[var(--orange)]"/>{item}</li>)}</ul></div><Detail title="Approach" text={selected.approach}/><Detail title="Risks / Edge Cases" text={selected.risks}/><Detail title="Tools" text={selected.tools.join(" / ")}/><Detail title="Outcome" text={selected.outcome}/></div></article></div>}
</>}
function Detail({title,text}:{title:string;text:string}){return <div><h4 className="detail-title">{title}</h4><p className="mt-2 leading-7 text-[var(--muted)]">{text}</p></div>}
