"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCommentDots,faPaperPlane,faXmark,faCheck } from "@fortawesome/free-solid-svg-icons";
import { siteConfig } from "@/lib/site";

type Status="idle"|"sending"|"sent"|"error";

export function ChatWidget(){
  const [open,setOpen]=useState(false);const [status,setStatus]=useState<Status>("idle");const panelRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>event.key==="Escape"&&setOpen(false);document.addEventListener("keydown",close);panelRef.current?.querySelector<HTMLElement>("input")?.focus();return()=>document.removeEventListener("keydown",close)},[open]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));try{const response=await fetch(`https://formsubmit.co/ajax/${siteConfig.email}`,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({...data,_subject:"New portfolio chat message",_template:"table"})});if(!response.ok)throw new Error("Submission failed");setStatus("sent");form.reset()}catch{setStatus("error")}}
  return <div className="fixed bottom-4 right-4 z-[65] sm:bottom-6 sm:right-6">
    {open&&<div ref={panelRef} className="chat-panel mb-3 w-[min(390px,calc(100vw-2rem))] overflow-hidden rounded-[1.5rem] border border-[var(--line)] bg-[var(--cream)] shadow-2xl" role="dialog" aria-modal="false" aria-labelledby="chat-title">
      <header className="flex items-center justify-between bg-[var(--ink)] p-5 text-white"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[var(--mint)] text-[var(--ink)]"><FontAwesomeIcon icon={faCommentDots}/></span><div><h2 id="chat-title" className="font-extrabold">Chat with Eduvigis</h2><p className="text-xs text-white/60">Usually replies by email</p></div></div><button onClick={()=>setOpen(false)} className="grid h-11 w-11 place-items-center rounded-full hover:bg-white/10" aria-label="Close chat"><FontAwesomeIcon icon={faXmark}/></button></header>
      {status==="sent"?<div className="grid min-h-80 place-items-center p-8 text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[var(--mint)]"><FontAwesomeIcon icon={faCheck}/></span><h3 className="display mt-5 text-2xl font-extrabold">Message sent.</h3><p className="mt-3 leading-6 text-[var(--muted)]">Thanks for reaching out. I&apos;ll reply to the email address you provided.</p><button className="button mt-6" onClick={()=>setStatus("idle")}>Send another</button></div></div>:<form onSubmit={submit} className="space-y-4 p-5"><div className="chat-bubble">Hi! Tell me about the role, project, or QA challenge you&apos;d like to discuss.</div><label className="field-label">Your name<input required name="name" autoComplete="name" maxLength={80} className="chat-input" placeholder="How should I address you?"/></label><label className="field-label">Email<input required type="email" name="email" autoComplete="email" maxLength={120} className="chat-input" placeholder="you@company.com"/></label><label className="field-label">Message<textarea required name="message" rows={4} maxLength={1500} className="chat-input resize-none" placeholder="Write your message..."/></label><input type="text" name="_honey" className="hidden" tabIndex={-1} autoComplete="off"/><input type="hidden" name="source" value="QA portfolio chat widget"/>{status==="error"&&<p role="alert" className="text-sm font-bold text-red-700">I couldn&apos;t send that message. Please try again or use the email button below.</p>}<button disabled={status==="sending"} className="button button-primary w-full disabled:cursor-wait disabled:opacity-60">{status==="sending"?"Sending...":"Send message"}<FontAwesomeIcon icon={faPaperPlane} className="h-4"/></button></form>}
    </div>}
    <button onClick={()=>setOpen(!open)} className="chat-launcher ml-auto flex h-14 items-center gap-3 rounded-full bg-[var(--orange)] px-5 font-extrabold text-[var(--ink)] shadow-[0_8px_0_var(--ink)]" aria-expanded={open} aria-label={open?"Close chat":"Chat with Eduvigis"}><FontAwesomeIcon icon={open?faXmark:faCommentDots}/><span>{open?"Close":"Chat with me"}</span></button>
  </div>;
}
