import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft,faArrowRight,faCheck } from "@fortawesome/free-solid-svg-icons";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { caseStudies,getCaseStudy } from "@/data/caseStudies";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return caseStudies.map(({slug})=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const study=getCaseStudy((await params).slug);return study?{title:study.title,description:study.summary}:{} }

export default async function CaseStudyPage({params}:Props){const study=getCaseStudy((await params).slug);if(!study)notFound();const index=caseStudies.findIndex(item=>item.slug===study.slug);const next=caseStudies[(index+1)%caseStudies.length];return <><Header/><main id="top" className="pt-[76px]"><article>
  <header className="border-b border-[var(--line)] bg-white py-20"><div className="case-detail-container"><Link href="/#case-studies" className="focus-ring inline-flex min-h-11 items-center gap-2 font-extrabold"><FontAwesomeIcon icon={faArrowLeft} className="h-3"/>All case studies</Link><p className="eyebrow mt-10 text-[var(--orange)]">QA Case Study</p><h1 className="display mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] sm:text-7xl">{study.title}</h1><p className="mt-5 text-sm font-extrabold uppercase tracking-wider text-[var(--muted)]">{study.applicationType}</p><p className="mt-7 max-w-3xl text-xl leading-8 text-[var(--muted)]">{study.summary}</p><div className="mt-7 flex flex-wrap gap-2">{study.testingTypes.map(type=><span className="pill bg-[var(--cream)]" key={type}>{type}</span>)}</div></div></header>
  <div className="case-detail-container py-16 sm:py-24"><CaseSection number="01" title="Overview"><p>{study.summary}</p><h3 className="detail-title mt-6">Testing objective</h3><p className="mt-2">{study.objective}</p></CaseSection><CaseSection number="02" title="My Role"><CheckList items={study.role}/></CaseSection><CaseSection number="03" title="Testing Scope"><div className="flex flex-wrap gap-2">{study.testingTypes.map(type=><span className="pill" key={type}>{type} Testing</span>)}</div></CaseSection><CaseSection number="04" title="Test Strategy"><p>{study.strategy}</p></CaseSection><CaseSection number="05" title="Key Test Scenarios"><CheckList items={study.scenarios}/></CaseSection><CaseSection number="06" title="Edge Cases"><CheckList items={study.edgeCases} muted/></CaseSection><CaseSection number="07" title="Defects / Risks Identified"><p className="mb-5 text-sm text-[var(--muted)]">Sanitized risk areas identified during coverage planning and testing:</p><CheckList items={study.risks} muted/></CaseSection><CaseSection number="08" title="QA Artifacts"><div className="grid gap-3 sm:grid-cols-2">{study.artifacts.map(item=><div key={item} className="rounded-xl border border-[var(--line)] bg-white p-4 font-bold">{item}<p className="mt-1 text-xs font-normal text-[var(--muted)]">Sanitized example; no confidential file linked</p></div>)}</div></CaseSection><CaseSection number="09" title="Tools"><div className="flex flex-wrap gap-2">{study.tools.map(tool=><span className="pill bg-white" key={tool}>{tool}</span>)}</div></CaseSection><CaseSection number="10" title="Outcome"><p>{study.outcome}</p></CaseSection>
    <Link href={`/case-studies/${next.slug}`} className="group mt-14 flex items-center justify-between gap-5 rounded-2xl bg-[var(--ink)] p-6 text-white sm:p-8"><div><span className="text-xs font-extrabold uppercase tracking-wider text-[var(--mint)]">Next case study</span><p className="display mt-2 text-2xl font-extrabold sm:text-3xl">{next.title}</p></div><FontAwesomeIcon icon={faArrowRight} className="h-5 transition-transform group-hover:translate-x-1"/></Link>
  </div></article></main><Footer/></>}

function CaseSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="case-detail-section"><div className="flex items-baseline gap-4"><span className="text-xs font-extrabold text-[var(--orange)]">{number}</span><h2 className="display text-3xl font-extrabold sm:text-4xl">{title}</h2></div><div className="case-detail-copy mt-6 leading-8 text-[var(--muted)]">{children}</div></section>}
function CheckList({items,muted=false}:{items:string[];muted?:boolean}){return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className={`flex gap-3 leading-7 ${muted?"text-[var(--muted)]":""}`}><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[var(--mint)] text-[.62rem] text-[var(--ink)]"><FontAwesomeIcon icon={faCheck}/></span>{item}</li>)}</ul>}
