import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft,faArrowRight,faCheck,faBug,faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { caseStudies,getCaseStudy,type CaseStudyFinding } from "@/data/caseStudies";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return caseStudies.map(({slug})=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const study=getCaseStudy((await params).slug);return study?{title:study.title,description:study.summary}:{} }

export default async function CaseStudyPage({params}:Props){const study=getCaseStudy((await params).slug);if(!study)notFound();const index=caseStudies.findIndex(item=>item.slug===study.slug);const previous=caseStudies[(index-1+caseStudies.length)%caseStudies.length];const next=caseStudies[(index+1)%caseStudies.length];return <><Header/><main id="top" className="pt-[76px]"><article>
  <header className="border-b border-[var(--line)] bg-white py-20"><div className="case-detail-container"><Link href="/#case-studies" className="focus-ring inline-flex min-h-11 items-center gap-2 font-extrabold"><FontAwesomeIcon icon={faArrowLeft} className="h-3"/>All case studies</Link><p className="eyebrow mt-10 text-[var(--orange)]">QA Case Study</p><h1 className="display mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] sm:text-7xl">{study.title}</h1><p className="mt-5 text-sm font-extrabold uppercase tracking-wider text-[var(--muted)]">{study.applicationType}</p><p className="mt-7 max-w-3xl text-xl leading-8 text-[var(--muted)]">{study.summary}</p><div className="mt-7 flex flex-wrap gap-2">{study.testingTypes.map(type=><span className="pill bg-[var(--cream)]" key={type}>{type}</span>)}</div></div></header>
  <div className="case-detail-container py-16 sm:py-24"><CaseSection number="01" title="Overview"><p>{study.summary}</p><h3 className="detail-title mt-6">Testing objective</h3><p className="mt-2">{study.objective}</p></CaseSection><CaseSection number="02" title="My Role"><CheckList items={study.role}/></CaseSection><CaseSection number="03" title="Testing Scope"><div className="flex flex-wrap gap-2">{study.testingTypes.map(type=><span className="pill" key={type}>{type} Testing</span>)}</div></CaseSection><CaseSection number="04" title="Test Strategy"><p>{study.strategy}</p>{study.localeMatrix&&<LocaleMatrix rows={study.localeMatrix}/>}</CaseSection><CaseSection number="05" title="Key Test Scenarios"><CheckList items={study.scenarios}/></CaseSection><CaseSection number="06" title="Edge Cases"><CheckList items={study.edgeCases} muted/></CaseSection><CaseSection number="07" title="Findings & Risks"><div className="grid gap-4">{study.findings.map(finding=><FindingCard key={finding.title} finding={finding}/>)}</div></CaseSection><CaseSection number="08" title="QA Artifacts"><div className="grid gap-3 sm:grid-cols-2">{study.artifacts.map(item=>item==="Sample Bug Report"?<Link href="/#qa-artifact" key={item} className="group rounded-xl border border-[var(--ink)] bg-white p-4 font-bold transition hover:-translate-y-1 hover:shadow-[0_5px_0_var(--ink)]">View Sample Bug Report <FontAwesomeIcon icon={faArrowRight} className="ml-2 h-3"/><p className="mt-1 text-xs font-normal text-[var(--muted)]">Related sanitized QA artifact</p></Link>:<div key={item} className="rounded-xl border border-[var(--line)] bg-white p-4 font-bold">{item}<p className="mt-1 text-xs font-normal text-[var(--muted)]">Sanitized example; no confidential file linked</p></div>)}</div></CaseSection><CaseSection number="09" title="Tools"><div className="flex flex-wrap gap-2">{study.tools.map(tool=><span className="pill bg-white" key={tool}>{tool}</span>)}</div></CaseSection><CaseSection number="10" title="Outcome"><p>{study.outcome}</p></CaseSection>
    <nav className="mt-12 grid gap-4 border-t border-[var(--line)] pt-8 sm:grid-cols-2" aria-label="Case study pagination"><Link href={`/case-studies/${previous.slug}`} className="group flex w-full max-w-sm items-center gap-4 rounded-2xl border border-[var(--ink)] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_7px_0_var(--ink)]"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[var(--ink)] text-white"><FontAwesomeIcon icon={faArrowLeft} className="h-4 transition-transform group-hover:-translate-x-1"/></span><div><span className="text-xs font-extrabold uppercase tracking-wider text-[var(--orange)]">Previous case study</span><p className="display mt-1 text-lg font-extrabold sm:text-xl">{previous.title}</p></div></Link><Link href={`/case-studies/${next.slug}`} className="group flex w-full max-w-sm items-center justify-between gap-4 rounded-2xl border border-[var(--ink)] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_7px_0_var(--ink)] sm:justify-self-end"><div><span className="text-xs font-extrabold uppercase tracking-wider text-[var(--orange)]">Next case study</span><p className="display mt-1 text-lg font-extrabold sm:text-xl">{next.title}</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[var(--ink)] text-white"><FontAwesomeIcon icon={faArrowRight} className="h-4 transition-transform group-hover:translate-x-1"/></span></Link></nav>
  </div></article></main><Footer/></>}

function CaseSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="case-detail-section"><div className="flex items-baseline gap-4"><span className="text-xs font-extrabold text-[var(--orange)]">{number}</span><h2 className="display text-3xl font-extrabold sm:text-4xl">{title}</h2></div><div className="case-detail-copy mt-6 leading-8 text-[var(--muted)]">{children}</div></section>}
function CheckList({items,muted=false}:{items:string[];muted?:boolean}){return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className={`flex gap-3 leading-7 ${muted?"text-[var(--muted)]":""}`}><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[var(--mint)] text-[.62rem] text-[var(--ink)]"><FontAwesomeIcon icon={faCheck}/></span>{item}</li>)}</ul>}
function FindingCard({finding}:{finding:CaseStudyFinding}){const defect=finding.type==="defect";return <article className={`finding-card ${defect?"finding-defect":"finding-risk"}`}><div className="flex flex-wrap items-center gap-2"><FontAwesomeIcon icon={defect?faBug:faTriangleExclamation} className="h-4"/><span className="text-xs font-black uppercase tracking-wider">{defect?"Defect found":"Risk covered"}</span>{finding.severity&&<span className="text-xs font-black uppercase">· {finding.severity}</span>}</div><h3 className="display mt-4 text-xl font-extrabold">{finding.title}</h3><div className="mt-5 grid gap-5 sm:grid-cols-2">{finding.scenario&&<FindingField label="Scenario" text={finding.scenario}/>} {finding.expected&&<FindingField label="Expected" text={finding.expected}/>} {finding.actual&&<FindingField label="Actual" text={finding.actual}/>} {finding.impact&&<FindingField label="Impact" text={finding.impact}/>} {finding.risk&&<FindingField label="Risk" text={finding.risk}/>} {finding.coverage&&<FindingField label="Coverage" text={finding.coverage}/>} {finding.expectedProtection&&<FindingField label="Expected protection" text={finding.expectedProtection}/>} {finding.resolution&&<FindingField label="Resolution" text={finding.resolution}/>} {finding.verification&&<FindingField label="Verification" text={finding.verification}/>}</div>{finding.artifactId&&<Link href="/#qa-artifact" className="focus-ring mt-6 inline-flex min-h-11 items-center gap-2 font-extrabold">View sample bug report <FontAwesomeIcon icon={faArrowRight} className="h-3"/></Link>}</article>}
function FindingField({label,text}:{label:string;text:string}){return <div><h4 className="detail-title">{label}</h4><p className="mt-2 leading-7 text-[var(--muted)]">{text}</p></div>}
function LocaleMatrix({rows}:{rows:{profileLanguage:string;browserLocale:string;expected:string}[]}){return <div className="mt-8 overflow-x-auto rounded-xl border border-[var(--line)] bg-white"><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">Sanitized locale testing matrix</caption><thead className="bg-[var(--ink)] text-white"><tr><th className="p-4">Profile language</th><th className="p-4">Browser locale</th><th className="p-4">Expected</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.profileLanguage}-${row.browserLocale}`} className="border-t border-[var(--line)]"><td className="p-4 font-bold">{row.profileLanguage}</td><td className="p-4">{row.browserLocale}</td><td className="p-4">{row.expected}</td></tr>)}</tbody></table></div>}
